### ISSUE TITLE
How to unpack multiple directories using hazardous

### ISSUE THREAD

**Issue by karthik22061993** [epsitec-sa/hazardous#7]
I have a requirement in my electron app. I want to unpack multiple directories. Currently I am using this inside package.json

```
"builder": " xxxx --asar.unpackDir=node_modules/regedit"
```
But what I want to do here is 

```
"builder": " xxxx --asar.unpackDir=node_modules/regedit , node_modules/@types/express"
```
Can I do this with hazardous?

**Comment by Skywalker13** [comment]
It's not the purpose of hazardous, sorry.
